const $=id=>document.getElementById(id);let preview=null;const TICKET_KEY="naxoraOwnerBootstrapTicket";
function norm(v=""){let s=String(v??"").normalize("NFKC").replace(/[\u200B-\u200D\uFEFF]/g,"").trim();if(s.length>=2&&((s.startsWith('"')&&s.endsWith('"'))||(s.startsWith("'")&&s.endsWith("'"))))s=s.slice(1,-1).trim();return s}
function readTicket(){const u=new URL(location.href),q=String(u.searchParams.get("ticket")||"").trim();if(q){sessionStorage.setItem(TICKET_KEY,q);u.searchParams.delete("ticket");history.replaceState({},document.title,`${u.pathname}${u.search}${u.hash}`)}return String(sessionStorage.getItem(TICKET_KEY)||"").trim()}
let ticket=readTicket();
function msg(t,type="error"){$("messageBox").hidden=false;$("messageBox").className=`message ${type}`;$("messageBox").textContent=t}
function busy(b,on,t="Please wait…"){b.dataset.o||=b.textContent;b.disabled=on;b.textContent=on?t:b.dataset.o}
async function api(url,o={}){const r=await fetch(url,{cache:"no-store",...o}),d=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(d.message||`${r.status} ${r.statusText}`);e.data=d;throw e}return d}
function secret(){return norm($("bootstrapSecret").value)}
function headers(){const h={"Content-Type":"application/json"};if(ticket)h["x-naxora-bootstrap-ticket"]=ticket;else h["x-naxora-bootstrap-secret"]=secret();return h}
function body(p={}){return JSON.stringify(ticket?{...p,bootstrapTicket:ticket}:{...p,bootstrapSecret:secret()})}
function save(d){for(const s of[sessionStorage,localStorage]){s.removeItem("naxoraToken");s.removeItem("naxoraInstituteId");s.removeItem("naxoraSession")}sessionStorage.setItem("naxoraToken",d.token);sessionStorage.setItem("naxoraInstituteId",d.institute.instituteId);sessionStorage.setItem("naxoraSession",JSON.stringify(d.session||{}))}
function ticketMode(){if(!ticket)return;const i=$("bootstrapSecret"),b=$("toggleSecret");i.value="";i.disabled=true;i.required=false;i.placeholder="Signed one-time bootstrap ticket active";b.disabled=true;b.textContent="Ticket";msg("Signed one-time bootstrap link active hai. Secret type karne ki zarurat nahi.","success")}
async function status(){try{const d=await api("/api/part1361/status");$("statusHeading").textContent=d.bootstrapAvailable?"First Owner setup available":"Bootstrap currently unavailable";$("statusBox").textContent=d.bootstrapAvailable?(ticket?"Signed bootstrap ticket detected. Owner setup start karein.":"Signed bootstrap URL use karein, ya private secret enter karein."):d.firstOwnerExists?"First Owner already exists. Common Login use karein.":`Bootstrap unavailable: ${d.bootstrapReasonCode}`;$("bootstrapForm").hidden=!d.bootstrapAvailable}catch(e){msg(e.data?.message||e.message)}}
async function verify(){if(!ticket&&!secret())throw new Error("Signed bootstrap URL ya private secret required.");const d=await api("/api/part1361/bootstrap/verify-secret",{method:"POST",headers:headers(),body:body({})});msg(d.receivedVia==="signed_ticket"?"Signed bootstrap ticket verified.":`Bootstrap secret matched (${d.receivedVia}).`,"success");return d}
$("bootstrapForm").addEventListener("submit",async e=>{e.preventDefault();const b=$("previewBtn");busy(b,true,"Verifying…");try{await verify();busy(b,true,"Generating…");const d=await api("/api/part1361/bootstrap/preview",{method:"POST",headers:headers(),body:body({instituteName:$("instituteName").value,ownerDisplayName:$("ownerDisplayName").value,identifier:$("identifier").value})});preview=d.preview;$("previewDetails").innerHTML=`<strong>${preview.instituteName}</strong><span>Institute ID: ${preview.instituteId}</span><span>Owner: ${preview.ownerDisplayName}</span><span>Login ID: ${preview.identifier}</span>`;$("confirmationText").value=preview.confirmationTextRequired||"";$("confirmPanel").hidden=false;msg("Preview ready.","success");$("confirmPanel").scrollIntoView({behavior:"smooth",block:"start"})}catch(e){msg(e.data?.message||e.message)}finally{busy(b,false)}});
$("confirmBtn").addEventListener("click",async()=>{const b=$("confirmBtn");busy(b,true,"Creating…");try{if(!preview)throw new Error("Pehle preview generate karein.");await verify();const d=await api("/api/part1361/bootstrap/confirm",{method:"POST",headers:headers(),body:body({previewId:preview.previewId,confirmationText:$("confirmationText").value,password:$("password").value})});save(d);sessionStorage.removeItem(TICKET_KEY);ticket="";$("bootstrapForm").hidden=true;$("confirmPanel").hidden=true;$("successPanel").hidden=false;$("finalInstituteId").textContent=d.institute.instituteId;msg("First Owner account successfully create ho gaya.","success")}catch(e){msg(e.data?.message||e.message)}finally{busy(b,false)}});
function toggle(i,b){const x=$(i),y=$(b);x.type=x.type==="password"?"text":"password";y.textContent=x.type==="password"?"Show":"Hide"}
$("toggleSecret").addEventListener("click",()=>toggle("bootstrapSecret","toggleSecret"));$("togglePassword").addEventListener("click",()=>toggle("password","togglePassword"));$("copyIdBtn").addEventListener("click",async()=>{try{await navigator.clipboard.writeText($("finalInstituteId").textContent.trim());msg("Institute ID copied.","success")}catch{msg("Copy nahi hua.")}});ticketMode();status();
