import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";
const root=path.dirname(fileURLToPath(import.meta.url)),serverPath=path.join(root,"backend/src/server.js"),shellPath=path.join(root,"backend/src/part119-unified-app-shell.js"),htmlPath=path.join(root,"frontend/naxora-unified-app.html");
const required=["backend/src/part120-common-login.js","backend/src/part124-role-consolidation.js","backend/src/part130-vani-academic-operations.js","backend/src/part131-vani-fees-finance-operations.js","backend/src/part132-vani-admissions-crm-operations.js","backend/src/part133-vani-communication-notifications.js","backend/src/part134-vani-reports-exports.js","backend/src/part135-vani-conversational-workflow-engine.js","frontend/naxora-workflow-vani.html","frontend/naxora-workflow-vani.css","frontend/naxora-workflow-vani.js","frontend/naxora-part135-global-vani-bridge.js"];
const marker="// ================= PART 135 — VANI CONVERSATIONAL WORKFLOW ENGINE =================",registration=`${marker}\nconst { registerPart135VaniConversationalWorkflowEngine } = await import("./part135-vani-conversational-workflow-engine.js");\nregisterPart135VaniConversationalWorkflowEngine({ app });`;
const moduleStart="  // PART 135 VANI WORKFLOW ENGINE MODULE START",moduleEnd="  // PART 135 VANI WORKFLOW ENGINE MODULE END",moduleBlock=`${moduleStart}\n  { key: "workflow-vani", label: "VANI Workflow Engine", description: "Multi-turn clarification, dependency-aware native workflows, per-step preview and exact confirmation.", category: "AI & VANI", route: "/workflow-vani", icon: "automation", roles: ["institute_owner", "branch_manager", "teacher", "student", "parent", "accountant", "counsellor", "staff"], alwaysAvailable: true, order: 325 },\n${moduleEnd}`;
const aliasStart="  // PART 135 VANI WORKFLOW ENGINE ALIASES START",aliasEnd="  // PART 135 VANI WORKFLOW ENGINE ALIASES END",aliasBlock=`${aliasStart}\n  "workflow vani": "workflow-vani",\n  "vani workflow": "workflow-vani",\n  "conversational vani": "workflow-vani",\n  "multi step workflow": "workflow-vani",\n  "exam workflow": "workflow-vani",\n  "assignment workflow": "workflow-vani",\n  "admission workflow": "workflow-vani",\n  "fee workflow": "workflow-vani",\n  "monthly report pack": "workflow-vani",\n  onboarding: "workflow-vani",\n  "part 135": "workflow-vani",\n${aliasEnd}`;
function fail(m){console.error(`\nPART 135 APPLY FAILED: ${m}\n`);process.exit(1)}function check(f){return spawnSync(process.execPath,["--check",f],{encoding:"utf8"})}function removeBetween(s,a,b){const x=a.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"),y=b.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");return s.replace(new RegExp(`\\s*${x}[\\s\\S]*?${y}\\s*`,"g"),"\n")}function regEnd(s,c){const i=s.indexOf(c);return i<0?-1:i+c.length}function notFound(s){let i=s.indexOf("app.use(notFound);");if(i<0)i=s.indexOf("app.use(notFound)");if(i<0){const c=Math.max(s.indexOf('"ROUTE_NOT_FOUND"'),s.indexOf("'ROUTE_NOT_FOUND'"));i=c>=0?s.lastIndexOf("app.use(",c):-1}return i}
for(const rel of required)if(!fs.existsSync(path.join(root,rel)))fail(`Required file missing: ${rel}`);for(const f of[serverPath,shellPath]){const r=check(f);if(r.status!==0)fail(`${path.relative(root,f)} syntax is broken before Part 135.\n${r.stderr||r.stdout}`)}
const original={server:fs.readFileSync(serverPath,"utf8"),shell:fs.readFileSync(shellPath,"utf8"),html:fs.readFileSync(htmlPath,"utf8")};let server=original.server;const escaped=marker.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");server=server.replace(new RegExp(`\\n*${escaped}\\nconst \\{ registerPart135VaniConversationalWorkflowEngine \\} = await import\\("\\.\\/part135-vani-conversational-workflow-engine\\.js"\\);\\nregisterPart135VaniConversationalWorkflowEngine\\(\\{ app \\}\\);\\n*`,"g"),"\n\n");const end=regEnd(server,"registerPart134VaniReportsExports({ app });");if(end<0)fail("Part 134 registration call not found. Apply and verify Part 134 first.");server=`${server.slice(0,end)}\n\n${registration}${server.slice(end)}`;
let shell=removeBetween(original.shell,moduleStart,moduleEnd);shell=removeBetween(shell,aliasStart,aliasEnd);const ma="  // PART 134 VANI REPORTS EXPORTS MODULE END",aa="  // PART 134 VANI REPORTS EXPORTS ALIASES END";if(!shell.includes(ma)||!shell.includes(aa))fail("Part 134 shell markers missing.");shell=shell.replace(ma,`${ma}\n${moduleBlock}`).replace(aa,`${aa}\n${aliasBlock}`);
let html=original.html.replace(/\s*<article><strong>135<\/strong><span>.*?<\/span><\/article>/g,"");if(!html.includes("<strong>135</strong><span>VANI workflows</span>")){const a=/(<article><strong>134<\/strong><span>.*?<\/span><\/article>)/;if(!a.test(html))fail("Part 134 progress card missing.");html=html.replace(a,`$1\n            <article><strong>135</strong><span>VANI workflows</span></article>`)}html=html.replace(/Part 134 VANI Reports and Exports active hai: Executive, Branch, Attendance, Academic, Finance, CRM, Communication aur Student 360 reports with CSV, JSON and print-ready HTML exports\./g,"Part 135 VANI Conversational Workflow Engine active hai: multi-turn clarification, dependency-aware plans, native previews, exact confirmations, pause/resume aur failure-safe execution.").replace(/Part 134 • operations \+ master-data \+ bulk import \+ academics \+ finance \+ CRM \+ communication \+ 12 reports actions/g,"Part 135 • Parts 130–134 native workflow orchestration + secure Parts 128–129 handoff");if(!html.includes("/naxora-part135-global-vani-bridge.js")){const a='<script src="/naxora-part134-global-vani-bridge.js"></script>';if(!html.includes(a))fail("Part 134 Global VANI bridge anchor missing.");html=html.replace(a,'<script src="/naxora-part135-global-vani-bridge.js"></script>\n  '+a)}
fs.writeFileSync(serverPath,server,"utf8");fs.writeFileSync(shellPath,shell,"utf8");fs.writeFileSync(htmlPath,html,"utf8");for(const f of[serverPath,shellPath]){const r=check(f);if(r.status!==0){fs.writeFileSync(serverPath,original.server);fs.writeFileSync(shellPath,original.shell);fs.writeFileSync(htmlPath,original.html);fail(`Syntax failed after integration. Originals restored.\n${r.stderr||r.stdout}`)}}const s=fs.readFileSync(serverPath,"utf8"),sh=fs.readFileSync(shellPath,"utf8"),h=fs.readFileSync(htmlPath,"utf8"),p134=s.indexOf("PART 134 — VANI REPORTS EXPORTS"),p135=s.indexOf("PART 135 — VANI CONVERSATIONAL WORKFLOW ENGINE"),p112=s.indexOf("PART 112 — RAZORPAY TEST MODE FOUNDATION"),p404=notFound(s);const valid=p134>=0&&p135>p134&&p112>p135&&p404>p112&&sh.includes('key: "workflow-vani"')&&sh.includes('"part 135": "workflow-vani"')&&h.includes('/naxora-part135-global-vani-bridge.js')&&h.indexOf('/naxora-part135-global-vani-bridge.js')<h.indexOf('/naxora-part134-global-vani-bridge.js')&&h.includes("<strong>135</strong><span>VANI workflows</span>");if(!valid){fs.writeFileSync(serverPath,original.server);fs.writeFileSync(shellPath,original.shell);fs.writeFileSync(htmlPath,original.html);fail("Part 135 integration verification failed. Originals restored.")}
console.log("\nPART 135 APPLIED SUCCESSFULLY");console.log("Part 135 registered after Part 134: PASS");console.log("Part 135 registered before Parts 112–119 routes: PASS");console.log("Part 119 VANI Workflow Engine module added: PASS");console.log("Part 119 workflow aliases added: PASS");console.log("Global VANI Part 135 bridge added before Part 134 bridge: PASS");console.log("Unified app Part 135 progress and honest boundary updated: PASS");console.log("server.js syntax: PASS");console.log("Next: node .\\VERIFY-PART135.js\n");
