import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";
const root=path.dirname(fileURLToPath(import.meta.url)),serverPath=path.join(root,"backend/src/server.js"),shellPath=path.join(root,"backend/src/part119-unified-app-shell.js"),htmlPath=path.join(root,"frontend/naxora-unified-app.html");
const required=["backend/src/part130-vani-academic-operations.js","frontend/naxora-academic-vani.html","frontend/naxora-academic-vani.css","frontend/naxora-academic-vani.js","frontend/naxora-part130-global-vani-bridge.js","backend/.env.part130.example"];
let failed=false;for(const rel of required){const ok=fs.existsSync(path.join(root,rel));console.log(`${ok?"PASS":"FAIL"} ${rel}`);if(!ok)failed=true}
for(const file of [serverPath,shellPath,path.join(root,"backend/src/part130-vani-academic-operations.js")]){const result=spawnSync(process.execPath,["--check",file],{encoding:"utf8"}),ok=result.status===0;console.log(`${ok?"PASS":"FAIL"} ${path.relative(root,file)} syntax`);if(!ok){console.error(result.stderr||result.stdout);failed=true}}
const source=fs.readFileSync(serverPath,"utf8");let p404=source.indexOf("app.use(notFound);");if(p404<0)p404=source.indexOf("app.use(notFound)");const markers=["PART 120 — COMMON LOGIN JWT AND ROLE ROUTING","PART 121 — OWNER MODULE CONSOLIDATION","PART 122 — TEACHER MODULE CONSOLIDATION","PART 123 — STUDENT MODULE CONSOLIDATION","PART 124 — PARENT STAFF AND BRANCH ROLE CONSOLIDATION","PART 125 — GLOBAL VANI MULTI STEP ACTIONS","PART 126 — NATIVE ADAPTERS AND CROSS MODULE E2E","PART 127 — FINAL DEMO ACCEPTANCE AND PROJECT FREEZE","PART 128 — VANI MASTER DATA ACTIONS","PART 129 — VANI BULK CSV JSON IMPORT","PART 130 — VANI ACADEMIC OPERATIONS","PART 112 — RAZORPAY TEST MODE FOUNDATION"];const positions=markers.map(marker=>source.indexOf(marker));const orderOk=positions.every(position=>position>=0)&&positions.slice(1).every((position,index)=>position>positions[index])&&p404>positions.at(-1);console.log(`${orderOk?"PASS":"FAIL"} Part 120 → 121 → 122 → 123 → 124 → 125 → 126 → 127 → 128 → 129 → 130 → Parts 112–119 → 404 order`);if(!orderOk)failed=true;
const shell=fs.readFileSync(shellPath,"utf8"),html=fs.readFileSync(htmlPath,"utf8");for(const [ok,label] of [[shell.includes('key: "academic-vani"'),"Part 119 VANI Academic Operations module exists"],[shell.includes('route: "/academic-vani"'),"Academic VANI route mapped"],[shell.includes('"bulk attendance": "academic-vani"'),"Bulk Attendance alias exists"],[shell.includes('"part 130": "academic-vani"'),"Part 130 alias exists"],[html.includes('/naxora-part130-global-vani-bridge.js'),"Global VANI Part 130 bridge exists"],[html.indexOf('/naxora-part130-global-vani-bridge.js')<html.indexOf('/naxora-part129-global-vani-bridge.js'),"Part 130 bridge loads before Part 129 bridge"],[html.includes("<strong>130</strong><span>VANI academics</span>"),"Unified app Part 130 progress exists"],[html.includes("Part 130 • 9 operational + 14 master-data + bulk import + 12 academic actions"),"Unified app Part 130 capability label exists"]]){console.log(`${ok?"PASS":"FAIL"} ${label}`);if(!ok)failed=true}process.exit(failed?1:0);