import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";
const root=path.dirname(fileURLToPath(import.meta.url));
const serverPath=path.join(root,"backend/src/server.js"),shellPath=path.join(root,"backend/src/part119-unified-app-shell.js"),htmlPath=path.join(root,"frontend/naxora-unified-app.html");
const required=["backend/src/part129-vani-bulk-import.js","frontend/naxora-bulk-import-vani.html","frontend/naxora-bulk-import-vani.css","frontend/naxora-bulk-import-vani.js","frontend/naxora-part129-global-vani-bridge.js","backend/.env.part129.example","templates/branches.csv","templates/courses.csv","templates/teachers.csv","templates/classes.csv","templates/students.csv","templates/parents.csv","templates/staff.csv","templates/linked-package.json"];
let failed=false;for(const rel of required){const ok=fs.existsSync(path.join(root,rel));console.log(`${ok?"PASS":"FAIL"} ${rel}`);if(!ok)failed=true}
for(const file of[serverPath,shellPath,path.join(root,"backend/src/part129-vani-bulk-import.js"),path.join(root,"frontend/naxora-bulk-import-vani.js"),path.join(root,"frontend/naxora-part129-global-vani-bridge.js")]){const result=spawnSync(process.execPath,["--check",file],{encoding:"utf8"});const ok=result.status===0;console.log(`${ok?"PASS":"FAIL"} ${path.relative(root,file)} syntax`);if(!ok){console.error(result.stderr||result.stdout);failed=true}}
const server=fs.readFileSync(serverPath,"utf8"),shell=fs.readFileSync(shellPath,"utf8"),html=fs.readFileSync(htmlPath,"utf8");let p404=server.indexOf("app.use(notFound);");if(p404<0)p404=server.indexOf("app.use(notFound)");const markers=["PART 120 — COMMON LOGIN JWT AND ROLE ROUTING","PART 121 — OWNER MODULE CONSOLIDATION","PART 122 — TEACHER MODULE CONSOLIDATION","PART 123 — STUDENT MODULE CONSOLIDATION","PART 124 — PARENT STAFF AND BRANCH ROLE CONSOLIDATION","PART 125 — GLOBAL VANI MULTI STEP ACTIONS","PART 126 — NATIVE ADAPTERS AND CROSS MODULE E2E","PART 127 — FINAL DEMO ACCEPTANCE AND PROJECT FREEZE","PART 128 — VANI MASTER DATA ACTIONS","PART 129 — VANI BULK CSV JSON IMPORT","PART 112 — RAZORPAY TEST MODE FOUNDATION"];const positions=markers.map(marker=>server.indexOf(marker));const orderOk=positions.every(position=>position>=0)&&positions.slice(1).every((position,index)=>position>positions[index])&&p404>positions.at(-1);console.log(`${orderOk?"PASS":"FAIL"} Part 120 → 121 → 122 → 123 → 124 → 125 → 126 → 127 → 128 → 129 → Parts 112–119 → 404 order`);if(!orderOk)failed=true;
for(const[ok,label]of[[shell.includes('key: "bulk-import-vani"'),"Part 119 VANI Bulk Import module exists"],[shell.includes('route: "/bulk-import-vani"'),"Bulk Import route mapped"],[shell.includes('"csv import": "bulk-import-vani"'),"CSV import alias exists"],[shell.includes('"part 129": "bulk-import-vani"'),"Part 129 alias exists"],[html.includes('/naxora-part129-global-vani-bridge.js'),"Global VANI Part 129 bridge exists"],[html.indexOf('/naxora-part129-global-vani-bridge.js')<html.indexOf('/naxora-part128-global-vani-bridge.js'),"Part 129 bridge loads before Part 128 bridge"],[html.includes("<strong>129</strong><span>VANI bulk import</span>"),"Unified app Part 129 progress exists"],[html.includes("Part 129 • 9 operational + 14 master-data + CSV/JSON bulk import"),"Unified app Part 129 capability label exists"]]){console.log(`${ok?"PASS":"FAIL"} ${label}`);if(!ok)failed=true}process.exit(failed?1:0);
